[mypy]
python_version = 3.10
files = src
ignore_missing_imports = True
disable_error_code = no-any-return, override, type-arg, misc, unused-ignore, attr-defined, arg-type, no-untyped-def, dict-item, import-untyped
